### ISSUE TITLE
Certificate verify failed

### ISSUE THREAD

**Issue by omarabid** [pwrdwnsys/loggly-rs#1]
I'm not certain if this is a problem with my setup or the package source code. I'm getting the following error

` { library: "SSL routines", function: "ssl3_get_server_certificate", reason: "certificate verify failed" }`

**Comment by pwrdwnsys** [comment]
Hi @omarabid - I haven't used Loggly for over two years now, and this library is unmaintained. I would guess your error is down to the old version of Hyper. Note that this library uses rustc_serialize which is also now deprecated, and I think the Loggly API has changed since this was written so even without the TLS-related errors, it probably would not work.
